spring.application.name=reader
# database URL
spring.datasource.url=jdbc:postgresql://ep-silent-sea-al94709x-pooler.c-3.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require

# credentials
spring.datasource.username=neondb_owner
spring.datasource.password=npg_dlmPkB5fuN1i

# the driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Auto-Generation (Crucial for building tables automatically) maybe remove this in the future????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true